### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by MykhailoRomanenko** [MykhailoRomanenko/homepage#5]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by SofiXeno** [comment]
Резюмé (фр. résumé), CV (лат. curriculum vitæ вимовляють курíкулюм вíте, що перекладається як «життєвий шлях») — вид документа, в якому подаються короткі відомості про навчання, трудову діяльність та професійні успіхи й досягнення особи, яка його складає.

Основна вимога до такого документа — вичерпність потрібних відомостей і лаконічність викладу.
