### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by MykhailoRomanenko** [MykhailoRomanenko/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by SofiXeno** [comment]
Близько 1 млн. років тому - Поява найдавнішої людини сучасного типу на нинішній території України

1 млн. - 9 тис. pp. до н.е. - Палеоліт.

IX— VI тис. до н.е. — Мезоліт.

VI —III тис. до н.е. - Неоліт.

IV-III тис. до н.е. — Енеоліт.

IV- III тис. до н.е. - Трипільська культура.

2500- 1800 pp. до н.е. - Мідний вік.

ІІ тис. - 800 pp. до н.е. - Бронзовий вік.

Кінець II - початок І тис. до н.е. - Розселення кіммерійців у степах Північного Причорномор'я.

VIII ст. до н.е. — Початок залізного віку.

VII ст. до н.е. - Поява скіфів у південноукраїнських степах.

VI — II ст. до н.е. - Розквіт скіфської держави.

VII ст. до н.е. - Початок грецької колонізації Причорномор'я.

V ст. до н.е. — Боспорське царство.

III ст. до н.е. - Поява у Північному Причорномор'ї сарматських племен, які панували там шість століть.

Близько 77 р. н.е. - Згадка про слов'ян-венедів римського історика Плінія Молодшого.

II —VII ст. - Розселення слов'ян. Утворення слов'янських родоплемінних союзів, перших державних утворень.

VIII – IX ст.. - Формування держави Київська Русь.

860-ті pp. - Просвітницька діяльність Кирила і Мефодія.

882 — 912 pp. — Князювання Олега в Києві після вбивства Аскольда.

912 —945 рр. — Князювання Ігоря.

941, 944 pp. — Походи князя Ігоря на Візантію.

945 — 964 pp. — Правління дружини Ігоря княгині Ольги.

964 —972 рр. — Князювання Святослава Ігоровича.

980—1015 pp. — Князювання Володимира Святославича.

988 —989 рр. — Прийняття християнства в Київській Русі.

1019—1054 рр. — Князювання Ярослава Мудрого.

1037 р. — Ярослав Мудрий заснував при Софіївському соборі першу бібліотеку на Русі.

1051 р. — Заснування Києво-Печерської лаври.

1037 — 1039 pp. — Митрополит Іларіон написав і проголосив перший літописний руський звід «Слово про закон і благодать».

1097 p.— Зібрання князів у Любечі.

1113 — 1125 pp. — Князювання Володимира Мономаха.

1113 р. — Літописний звід Нестора «Повість времен-них літ».

1185 р. — Створення «Слова о полку Ігоревім».

1187 р. — Вперше в літописі згадується назва «Україна».

1199 р. — Волинський князь Роман Мстиславич об'єднав Галицьку і Волинську землі; утворення Галицько-Волинського князівства.

1199—1205 рр. — Князювання Романа Мстиславича.

Близько 1201 — 1264 pp. — Роки життя князя Данила Галицького.

1238 р. — Військо Данила Галицького розгромило хрестоносців під Дорогочином.

1240 p., листопад — 6 грудня 1241 р. — Київ захопили татаро-монголи.

1241 р. — Вторгнення монгольської орди на територію Галицько-Волинського князівства.

1323 р. — Литва захопила Берестейську та Дорогочинську землі.

1323—1340 pp. — Князювання Юрія II (Болеслава Тройденовича — останнього Галицько-Волинського князя).

1340—1377 рр. — Князювання Любарта Гедиміновича на Волині.

1345—1377 pp. — Князювання великого князя Ольґерда в Литві.

1349 р. — Польща захопила більшу частину Галичини.

1362 р. — Перемога військ Литви над Золотою Ордою в урочищі Сині Води (Поділля). Входження до складу Литви Київщини і Поділля.

1375 р. — Створення Галицької митрополії.

1377—1434 pp. — Князювання Ягайла Ольгердовича (з 1386 р. — польський король).

1385 р. — Кревська унія.

1387 р. — Польща остаточно загарбала Галичину.

1410, 15 липня — Грюнвальдська битва.

1413 р. — Городельська унія між Литвою і Польщею.

1392 — 1430 pp. — Князювання великого князя Вітовта у Литві.

1490-і pp. — Перші згадки в документальних джерелах про українських козаків.

1490—1492 рр. — Повстання проти шляхти під керівництвом Мухи в Галичині.

1526— 1608 pp. — Роки життя Костянтина Острозького — засновника Острозької академії.

1550—1563 pp. — Гетьманування Дмитра Вишневецького.

1552 — 1554 pp. — Заснування Запорізької Січі на о. Мала Хортиця. Похід Д.Вишневецького (Байди) в Крим.

1556—1561 pp. — Переклад українською мовою Пересопницького Євангелія.

1569 р. — Люблінська унія. Утворення Речі Посполитої.

1596— 1647 pp. — Роки життя Петра Могили — митрополита Київського, засновника Києво-Могилянської колегії (1632 p.).

1591 —1593 рр. — Козацько-селянське повстання під проводом К.Косинського.

1594—1596 рр. — Козацько-селянське повстання на чолі з С.Наливайком.

1595—1657 pp. — Роки життя Богдана Зиновія Хмельницького — гетьмана України (1648— 1657 pp.).

1596 р. — Берестейська церковна унія.

1616—1622 pp. — Гетьманування Петра Конашевича-Сагайдачного.

1621 р. — Битва під Хотином.

1625-1638 pp. - Козацько-селянські повстання під керівництвом М.Жмайла, Т.Трясила. І.Сулими, Я.Острянина, Д.Гуні.

1648 —1676 рр. — Національно-визвольна революція українського народу проти шляхетської Польщі.

1648, травень, вересень — Перемога козацького війська над поляками під Жовтими Водами, Корсунем та Пилявцями.

1649 р. — Розгром польського війська під Зборовом. Зборівська мирна угода.

1651 р. — Поразка козацького війська в битві під Берестечком. Білоцерківський договір.

1652 р. — Військо Б.Хмельницького розгромило під Батогом польську армію.

1653 р. — Битва під Жванцем.

1654, 8 (18) січня — Переяславсько-московська угода.

1654, березень — Березневі статті. Політичний та правовий статус України в складі Московської держави.

1657, 27 липня (6 серпня н. ст.) - Смерть Богдана Хмельницького. Обрання гетьманом Юрія Хмельницького.

1657, жовтень — 1659 pp. — Гетьманування Івана Виговського.

1658 р. — Гадяцький договір.

1659 р. — Розгром московських військ під Конотопом.

1659—1663 pp. — Друге гетьманування Ю.Хмельницького.

1659 р. — Переяславські статті Ю.Хмельницького.

1660 р. — Слободищенський трактат — угода Ю.Хмельницького з Польщею.

1661 р. — Відкриття університету у Львові.

1663—1668 pp. — Гетьманування І.Брюховецького на Лівобережній Україні.

1663— 1665 pp. — Гетьманування П.Тетері на Правобережній Україні.

1665 р. — Московські статті. Обмеження автономії України.

1665— 1676 рр. — Гетьманування П.Дорошенка.

1667 р. — Андрусівське перемир'я між Московщиною і Польщею. Поділ України на Лівобережну (у складі Московщини) і Правобережну (у складі Польщі).

1668—1672 рр. — Гетьманування Д.Многогрішного.

1669, березень — Глухівські статті.

1672—1687 pp. — Гетьманування І.Самойловича на Лівобережній Україні.

1677 — 1681 pp. — Російсько-турецька війна за Лівобережну Україну. Трете гетьманування Ю.Хмельницького.

1681 р. — Бахчисарайський договір між Московщиною, Туреччиною і Кримським ханством.

1685 р. — Підпорядкування Київської митрополії московському патріарху.

1686 р. — «Трактат про вічний мир» між Московщиною і Польщею.

1687—1709 рр. — Гетьманування І.Мазепи. Коломацькі статті.

1708, жовтень — Перехід І.Мазепи на бік Карла XII.

1708, 2 листопада — Московські війська розгромили гетьманську столицю м.Батурин.

1708—1722 рр. — Гетьманування І.Скоропадського.

1709 р. — Московська армія зруйнувала Чортомлицьку Січ. Полтавська битва.

1710, квітень — Обрання гетьманом України П.Орлика в Бендерах.

1710 р. — Конституція П.Орлика.

1711 р. — Заснування Олешківської Січі.

1722 р. — Заснування першої Малоросійської колегії.

1722 —1724 рр. — Гетьманування П.Полуботка.

1727—1734 рр. — Гетьманування Д.Апостола.

1734 — 1750 pp. — Правління гетьманського уряду.

1734 р. — Повернення запорожців в Україну. Заснування Нової Січі на р. Підпільній.

1745 р. — Загибель ватажка карпатських опришків Олекси Довбуша.

1750—1764 рр. — Гетьманування К.Розумовського.

Близько 1690—1803 рр. — Петро Калнишевський — останній кошовий отаман Запорізької Січі (1762, 1765 — 1775 рр.).

1764 р. — Ліквідація Гетьманства і створення другої Малоросійської колегії.

1768 p. — Початок Коліївщини на Правобережній Україні.

1772 р. — Перший поділ Польщі. Приєднання Східної Білорусі до Росії, а Галичини до Австрії.

1775 р. — Росія ліквідувала Запорізьку Січ. Австрія загарбала Буковину.

1775— 1828 pp. — Задунайська Січ.

1781 р. — Ліквідація полкового територіально-адміністративного поділу на Лівобережжі.

1783 р. — Приєднання Кримського ханства до Росії. Царський указ про закріпачення селян на Лівобережній і Слобідській Україні.

1783 р. — Заснування Севастополя.

1788 р. — Формування Чорноморського козацького війська.

1793 р. — Другий поділ Польщі. Росія захопила Правобережну Україну.

1795 р. — Третій поділ Польщі. Росія захопила Західну Волинь, Західну Білорусію, Литву і Курляндію.

1805 р. — Відкриття Харківського університету.

1813— 1835 pp. — Антикріпосницький рух під проводом Устима Кармалюка.

1825, 25 грудня — Повстання Чернігівського полку. Взяття Василькова.

1828 р. — Повернення запорізьких козаків з Туреччини. Утворення Азовського війська.

1834, 15 липня — Відкриття Київського університету ім. Св. Володимира.

1837 р. — «Руська трійця» видала в Будапешті літературний альманах «Русалка Дністрова».

1846 p., січень — 1847 p., початок — Діяльність Кирило-Мефодіївського братства.

1846 р. — Видання в Москві «Історії русів».

1848 р. — Створення першої української політичної організації — Головної Руської Ради у Львові. Ліквідація панщини в Східній Галичині і Буковині.

1851 р. — Розпуск Головної Руської Ради.

1861, січень — 1862 р. — Видання в Петербурзі щомісячного громадсько-політичного і літературного журналу українською мовою «Основа».

1863, 18 липня — Валуєвський указ про обмеження видання книг і заборону навчання у школах українською мовою.

1865 р. — Відкриття Новоросійського університету в Одесі.

1866—1934 pp. — Роки життя Михайла Грушевського. 1868 p., 8 грудня — Заснування товариства «Просвіта» у Львові.

1873 р. — Заснування літературного товариства ім. Т.Шевченка у Львові.

1875 р.— Заснування Чернівецького університету.

1876 р. — Олександр II підписав Емський указ, що забороняв видавати та ввозити з-за кордону літературу українською мовою.

1885 p.— Заснування Народної Ради у Львові.

1890 р. — Утворення Русько-української радикальної партії в Східній Галичині.

1891 — 1898 — Діяльність «Братства тарасівців» — першої української політичної організації, що стояла на засадах самостійності України.

1899 р. — Утворення Української національно-демократичної та Української соціал-демократичної партій в Галичині.

1900 р. — Утворення в Харкові Революційної української партії.

1900 р. — Заснування в Східній Галичині перших військово-патріотичних організацій «Січ» з ініціативи К. Трильовського.

1903 р. — Видання у Відні «Біблії» українською мовою:

1904 р. — Утворення Української радикальної та Української демократичної партій.

1905, 14 червня — Повстання на броненосці «Потьомкін».

1905, 14 листопада — Повстання на крейсері «Очаків» на чолі з лейтенантом П.Шмідтом.

1906, 27 квітня — 8 липня — Діяльність І Державної думи та Української думської громади.

1906, 9 листопада — Указ про вільний вихід селян з общини.

1907, 20 лютого — 8 червня — Діяльність II Державної думи та Української громади в ній.

1908 р. — Утворення Товариства українських поступовців.

1914 p., 19 липня (1 серпня н.ст.) — Початок Першої світової війни. Створення Головної української ради.

1914 p., 10 серпня — 12 вересня — Галицька битва армій Росії і Австро-Угорщини. Вступ російських військ на територію Східної Галичини.

1914 p., серпень — вересень — Утворення легіону Українських Січових стрільців.

1914, кінець — Росія утворила Галицько-Буковинське генерал-губернаторство (ліквідовано в серпні 1917 p.).

І917р.

Лютий — Початок революції в Російській імперії.

4(17) березня — Утворення Української Центральної Ради.

6 (19) квітня — Початок роботи Всеукраїнського Національного Конгресу и Києві.

10 (23) червня — І Універсал Центральної Ради.

15 червня — Створення Генерального Секретаріату Центральної Ради.

3(16) липня — II Універсал Центральної Ради.

25 жовтня — Центральна Рада утворила Комітет з охорони революції в Україні.

7 (20) листопада — III Універсал Центральної Ради. Проголошення Української Народної Республіки (УНР).

4 (17) грудня — Ультиматум Раднаркому РСФРР Центральній Раді.

11 — 12 грудня — Всеукраїнський з'їзд Рад у Харкові. Проголошення України Радянською республікою.

27 грудня — Вибори до Українських установчих зборів.

1918 р.

22 січня — IV Універсал Центральної Ради.

29 січня — Бій під Крутами.

9 лютого — Підписання мирного договору УНР з країнами австро-німецького блоку.

9 лютого — Війська М.Муравйова захопили Київ. Більшовицькі погроми та масові розстріли. Переїзд Центральної Ради до Житомира.

1 березня — Прийняття Законів про державний герб УНР, про грошову систему, про громадянство.

18—19 лютого — Вступ німецьких військ в Україну.

2 березня — Вступ німецьких і українських військ до Києва.

29 квітня — УЦР ухвалила Конституцію УНР, обрання М. Гру шевського Президентом УНР. Гетьманський переворот, проголошення П.Скоропадського гетьманом України.

18 жовтня — Створення Української Національної Ради у Львові.

13 листопада — Проголошення Західноукраїнської Народної Республіки (ЗУНР).

14 листопада — Утворення Директорії УНР. Заснування Всеукраїнської Академії наук у Києві.

14 грудня — Гетьман П.Скоропадський зрікся влади на користь Директорії.

18 грудня — Десант країн Антанти в Одесі.

1919 р.

22 січня — Акт злуки УНР і ЗУНР.

11 лютого — С.Петлюра став головою Директорії УНР (після відставки В.Винниченка).

6—10 березня — НІ Всеукраїнський з'їзд Рад у Києві. Утворення УСРР. Схвалення Конституції УСРР.

Травень — червень — Східну і Південну Україну окупували війська Денікіна.

Жовтень — Армія Денікіна зайняла Правобережну Україну.

7 листопада — Початок третього наступу більшовиків на Україну.

11 грудня — Створення Всеукраїнського революційного комітету на чолі з Г.Петровським, який 19 січня 1920 р. перетворено на Раднарком УСРР на чолі з Х.Раковським.

16 грудня — Більшовики втретє захоплюють Київ.

1920 р.

22 квітня — Варшавський договір між УНР і Польщею. 25 квітня — Початок польсько-радянської війни. 6 травня — Польські та українські війська зайняли Київ.

26 травня — Контрнаступ більшовиків на Україну.

12 червня — Більшовики зайняли Київ.

28 жовтня — 17 листопада — Більшовицький наступ проти Врангеля в Криму.

Грудень — Союзний договір між УСРР і РСФРР про військову і господарську співпрацю.

1921 р.

Березень — Введення нової економічної політики (НЕП).

18 березня — Ризький мирний договір між Польщею і РСФРР та УСРР.

Серпень — Більшовики розгромили загони Н.Махна.

4 — 29 листопада — Другий Зимовий похід армії УНР під проводом Ю.Тютюнника. 23 листопада під Базаром розстріляно 359 його учасників.

1922 р.

Осінь 1921 — весна 1922 pp. — Голод на півдні України.

2 січня — Угоди між УСРР і Туреччиною про дружбу і співробітництво.

26 жовтня — Рішення про утворення у Львові нелегального (таємного) українського університету.

30 грудня — Утворення СРСР.

1923 р.

1 серпня - Постанова ВУЦВК і РНК УСРР про українізацію.

1924 р.

Березень — Повернення М.Гру шевського з еміграції до Києва.

12 жовтня — Утворення Молдавської АСРР у складі УСРР.

1925 р.

5 квітня — Обрання Л.Кагановича генеральним секретарем ЦК КП(б)У.

1926 р.

Травень — Звинувачення О.Шумського в націоналістичному ухилі.

10 листопада — Відкриття Українського наукового інституту в Берліні.

1927 р.

7 червня — Засудження Комуністичної партії Західної України (КПЗУ) за націоналістичний ухил («шумськізм»).

1928 р.

Березень — травень — «Шахтинська справа». Безпідставні звинувачення групи інженерно-технічних працівників Донбасу в шкідництві.

14 липня — Обрання на посаду генерального секретаря ЦК КП(б)У С.Косіора.

1929 р.

27 січня — 3 лютого — Створення Організації українських націоналістів (ОУН) на конгресі у Відні.

Липень — вересень — Арешти визначних діячів української науки і культури за належність до Спілки визволення України (СВУ).

1930 р.

1929— 1930 pp. — Перша фаза колективізації і «розкуркулєння» в Україні.

9 березня — 19 квітня — Процес Спілки визволення України (СВУ) в Харкові.

1931 р.

Лютий — Арешти колишніх діячів УНР — В.Голубовича, П.Христюка, М.Шрага та ін. Депортація М.Грушевського до Москви.

1932 р.

Весна — Початок голодомору в Україні.

9 лютого — Постанова ВУЦВК про утворення областей.

7 серпня — Постанова ВЦВК і РНК СРСР, написана Сталіним, «Про охорону майна державних підприємств, колгоспів і кооперативів та про зміцнення суспільної (соціалістичної) власності» («Закон про п'ять колосків»).

Жовтень — Пуск першої лінїи-Дніпрогесу.

1 листопада — Початок «роботи» надзвичайної хлібозаготівельної комісії на чолі з В.Молотовим.

1933 р.

Січень — жовтень — Масовий голод в Україні. 14 січня — Призначення П.Постишева секретарем ЦККП(б)У.

13 травня — Самогубство М.Хвильового. 7 липня — Самогубство М.Скрипника.

1934 р.

21 січня — Ухвала про перенесення столиці УСРР з Харкова до Києва.

Кінець року — Арешт діячів літератури України Г.Косинки, Д.Вальківського, К.Буревія, О.Близька, В.Підмогильного, Є.Плужника та ін.

1935 р.

Квітень — вересень — Арешт групи неокласиків — М.Зєрова, П.Филиповича, А.Лебедя, М.Драй-Хмари, М. Рильського та ін.

1936 р.

Весна — Підірвано Михайлівський Золотоверхий собор XII ст. у Києві. (До 1939 р. понад 70 % церков в Україні були закриті або зруйновані.)

Квітень — Арешт і розстріл у 1937 р. Ю.Коцюбинського нібито як керівника українського троцькістського центру.

Жовтень — Початок масових репресій і терору в Україні (так звана єжовщина), що тривали до кінця 1938 р.

1937 р.

25 — 30 січня — Надзвичайний XIV Всеукраїнський з'їзд Рад схвалив нову Конституцію УРСР.

1938 р.

27 січня — Призначення М.Хрущова першим секретарем ЦК КП(б)У.

24 квітня — Впровадження російської мови як обов'язкової в усіх школах УРСР.

1939 р.

15 березня — Проголошення самостійності Карпатської України, президентом якої було обрано А.Волошина.

15—18 березня — угорські війська окупували Карпатську Україну.

23 серпня — Німецько-радянський пакт про ненапад і таємна угода про розподіл сфер впливу у Східній Європі.

28 вересня — Договір про дружбу і кордон між СРСР і Німеччиною.

26 — 27 жовтня — Народні збори Західної України прийняли Декларацію про входження Західної України до складу УРСР.

1—2 листопада — Верховна Рада СРСР прийняла рішення про прийняття до СРСР Західної України і Західної Білорусі.

1940 р.

28 червня — Червона армія зайняла Північну Буковину й Бсссарабію; включення їх до УРСР.

2 серпня — Закон Верховної Ради СРСР про включення Північної Буковини і північної та південної частини Бессарабії до складу УРСР.

1941 р.

22 червня — "Напад Німеччини на СРСР.

26 червня — Подвиг М.Гастелло, в екіпажі якого були українці О.Бурденюк, Г.Скоробагатий.

30 червня — Проголошення у Львові ОУН(Б) відновлення української державності та утворення Українського державного правління на чолі з Я.Стецьком.

5 липня — 19 вересня — Оборона Києва.

Літо — Партизанські дії «Поліської Січі» на чолі з Т.Бульбою-Боровцем проти німців і радянських військових частин.

20 серпня — Створення рейхскомісаріату «Україна» на чолі Е.Кохом.

Вересень — Німці заарештували багатьох членів ОУН на чолі з С.Бандсрою.

Осінь, зима — Німецькі спеціальні частини «СС» знищили понад 150 тис. євреїв у Бабиному Яру, понад 30 тис. — у Дробицькому Яру, всього близько 900 тис. євреїв.

30 жовтня — 4 липня 1942 р. — Героїчна оборона Севастополя, що тривала 250 днів і ночей.

Осінь — Евакуація з України в тил понад 550 великих підприємств.

1942 р.

Лютий — Початок примусового вивезення українців до Німеччини.

Травень — Поразка Червоної армії під Харковом та в Криму.

22 липня — Фашисти окупували всю територію України.

Жовтень — Створення Української повстанської армії (УПА).

1943 р.

19 листопада 1942 р. — 2 лютого 1943 р. — Контрнаступ. Червоної армії під Сталінградом.

Травень — жовтень — Рейд партизанського загону С.Ковпака з Путивля у Карпати.

5 липня — 23 серпня — Битва на Курській дузі. Вигнання німецьких військ із Харкова (23 серпня).

Вересень — листопад — Битва за Дніпро. Вигнання німецьких військ із Києва (6 листопада).

1944 р.

28 жовтня — Визволення всієї території України від фашистів.

18 — 22 липня — Бій під Бродами. Червона армія розбила дивізію «Галичина».

Травень — липень — Початок боротьби УПА з частинами Червоної армії.

1945 р.

29 червня — Чехословацький договір у Москві. Повернення Закарпатської України Радянській Україні.

26 квітня — Входження УРСР на конференції в Сан-Франциско як члена-засновника до ООН.

16 серпня — Договір між СРСР і Польщею про кордон уздовж Бугу і на схід від Сяну.

1946 р.

8—10 березня — Собор греко-католицької церкви у Львові скасував унію греко-католицької церкви з Римом і підпорядкував її Російській православній церкві.

1946 — 1947 pp. — Голод в Україні.

1947 р.

З березня — Л.Каганович призначений першим секретарем ЦК КП(б)У і почав «чистку» серед української інтелігенції, звинувачуючи її в «буржуазному націоналізмі».

1948 р.

Січень — М.Хрущов призначений першим секретарем ЦК КП(б)У.

1949 р.

Квітень — Наукове товариство ім. Т.Шевченка у Мюнхені почало видавати «Енциклопедію українознавства».

Грудень — Обрання Л.Мельникова першим секретарем ЦК. КП(б)У.

1950 р.

Березень — Початок збирання підписів під Стокгольмською відозвою до народів світу про заборону атомної зброї. Протягом 1950— 1951 pp. її підписали в Україні понад 20 млн. чоловік.

1951 р.

Червень — Друга декада української літератури і мистецтва в Москві. Розгромна критика вірша В.Сосюри «Любіть Україну».

1953 p.

5 березня — Помер Й.Сталін.

24 червня — Пленум ЦК КПУ увільнив Л.Мельникова від обов'язків першого секретаря ЦК і призначив на його місце О.Кириченка.

1954 р.

19 лютого — Введення Кримської області до УРСР на основі рішення Президії Верховної Ради СРСР і з нагоди святкування 300-річчя «возз'єднання» України з Росією. „

12 травня - УРСР стає членом ЮНЕСКО і Міжнародної Організації Праці.

1956 р.

14 — 25 лютого — XX з'їзд КПРС, що накреслив за

ходи щодо десталінізації.

Серпень — вересень — Початок реабілітації незаконно репресованих українських громадян.

1959 р.

15 жовтня — Агент КДБ Б.Сташинський вбив С.Бандеру.

Грудень — Початок видання «Української Радянської

Енциклопедії».

1960 р.

Лютий — Введення в дію першого атомного реактора в Україні.

Жовтень — Створення у Києві Товариства культурних зв'язків з українцями за кордоном.

1961 р.

Січень — Суд у Львові над членами Української робітничо-селянської спілки (Л.Лук'яненком, І.Кандибоюта ін.).

22 травня — Початок вшанування пам'яті Т.Шевченка у день перенесення його праху в Україну.

Жовтень — XXII з'їзд КПРС схвалив нову програму «побудови комунізму» й проголосив політику «злиття націй».

1962 р.

11 — 15 серпня — Політ навколо землі українського космонавта П.Поповича.

1963 р.

Липень — Увільнення М.Підгорного й обрання П.Шелеста першим секретарем ЦК КПУ.

1964 р.

14 жовтня — Усунення М.Хрущова з посади першого секретаря ЦК КПРС і призначення на його місце Л.Брежнєва.

1965 р.

Літо — осінь — Перша хвиля арештів серед передової української інтелігенції.

26 серпня — Арешт братів М. і Б.Горинів, О.Заливахи, С.Караванського, М.Масютка та інших правозахисників в Україні.

1966 р.

Листопад — Серійне виробництво найбільшого у світі літака «Антей».

16—19 листопада — V з'їзд Спілки письменників України виступив на захист української мови.

1968 р.

Квітень — Протест 139 діячів української інтелігенції керівництву СРСР проти арештів в Україні й обмежень національної культури.

1971 р.

Січень — травень — Друга смуга репресій в Україні, жертвою яких стали В.Чорновіл, Є.Сверстюк, І.Світличний, І.Дзюба, В.Стус та ін.

1972 р.

25 травня — Увільнення П.Шелеста від обов'язків першого секретаря ЦК КПУ і обрання на цю посаду В.Щербицького.

1972—1973 рр. — Судові політичні процеси в Україні.

1973 p.

Травень — Початок наступу компартійних структур проти української культури. Критика на адресу Р.Іваничука, С.Плачинди, І.Білика та інших діячів культури України.

1976 р.

Листопад — У Києві створено Українську групу сприяння виконанню Гельсінських угод на чолі з М.Руденком.

1978 р.

20 квітня — Верховна Рада УРСР ухвалила нову Конституцію УРСР.

1980 р.

Січень — Початок видання за кордоном «Вісника репресій в Україні».

1982 р.

Травень — Відзначення в Україні 1500-річчя заснування Києва.

1985 р.

11 березня — М.Горбачова обрано генеральним секретарем ЦК КПРС. Початок процесу лібералізації.

1986 р.

26 квітня — Катастрофа на Чорнобильській АЕС.

1988 р.

Літо — Відзначення 1000-річчя хрещення Київської Русі.

1989 р.

Лютий — Установчий з'їзд Товариства української мови ім. Т.Шевченка.

Вересень — Установчий з'їзд Народного Руху України за перебудову.

28 жовтня — Верховна Рада УРСР ухвалила Закон про державний статус української мови.

Жовтень — Установчі збори відновленого Наукового товариства ім. Т.Шевченка у Львові.

1990 р.

Квітень — Створення Української республіканської партії.

16 липня — Верховна Рада УРСР прийняла «Декларацію про державний суверенітет України».

18 березня — Вибори до Верховної Ради України та місцевих Рад.

1991р.

24 серпня — Верховна Рада України проголосила Акт про державну незалежність України.

1 грудня — Всенародний референдум на підтвердження Акта про державну незалежність України. Л.Кравчука обрано Президентом України.

8 грудня — Зустріч керівників України, Росії, Білорусі у Біловезькій пущі. Біловезькі угоди про припинення існування СРСР і створення Співдружності Незалежних Держав (СНД).

1992 р.

28 січня — Сесія Верховної Ради України прийняла постанову про Державний прапор України — синьо-жовтий стяг.

Листопад — Відставка уряду В.Фокіна та формування нового уряду Л.Кучми.

1993 р.

17 червня — Угода між Російською Федерацією і Україною про невідкладні заходи щодо формування Чорноморського флоту Росії і Військово-Морських Сил України на базі Чорноморського флоту.

16 липня — Постанова Верховної Ради України «Про Постанову Верховної Ради Російської Федерації «Про статус міста Севастополя»».

24 вересня — Президент України дав згоду на входження держави до економічного союзу незалежних держав як «асоційованого члена».

9—10 вересня — Проведення в Києві Міжнародної наукової конференції «Голодомор 1932—1933 років в Україні: причини і наслідки».

1994 р.

14 січня — Президенти України, Росії та США підписали в Москві договір, що передбачав ліквідацію на території України 176 міжконтинентальних ракет і 1500 ядерних боєголовок.

Березень — Вибори до Верховної Ради України та місцевих Рад.

Літо — осінь — У Криму сформувалася найбільша організація, яка об'єднує українство на півострові, — Український громадський конгрес.

10 липня — Президентом України обрано Л.Кучму.

27 — 28 жовтня — Проведення в Києві Міжнародної наукової конференції «Україна у Другій світовій війні: уроки історії та сучасність».

1995 р.

8 червня — Президент України Леонід Кучма і Голова Верховної Ради Олександр Мороз підписали Конституційну угоду.

1996 р.

28 червня — Прийняття нової Конституції України.

25 серпня — Указ Президента України Л.Кучми «Про грошову реформу в Україні».

2—16 вересня — Введення в Україні національної грошової одиниці — гривні. Проведення грошової ре-форми.

1997 р.

9 липня — Підписання Хартії про особливе партнерство між Україною і НАТО.

16 липня — Призначення прем'єр-міністром України Валерія Пустовойтенка.

28 серпня — Урочисте представлення нового складу Кабінету Міністрів України.

1998 р.

29 березня — Вибори до Верховної Ради України.

1999 р.

Листопад — Вибори Президента України. 22 грудня — Призначення прем'єр-міністром України Віктора Ющенка.

2000 р.

16 квітня - Всеукраїнський референдум.

2004 р.

22 листопада - грудень 2004 - Помаранчева революція.

2014 р.

21 листопада 2013 - лютий 2014 - Революція гідності.

березень 2014 - Анексія Криму Росією.

7 червня 2014 р. - Інаугурація Президента Петра Порошенка.
