### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by MykhailoRomanenko** [MykhailoRomanenko/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by SofiXeno** [comment]
a.glybovets@ukma.edu.ua
gumenna@ukma.edu.ua
https://www.instagram.com/binary_studio_academy/
