### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by MykhailoRomanenko** [MykhailoRomanenko/homepage#8]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by SofiXeno** [comment]
Замо́вник — фізична чи юридична особа, розпорядник грошових коштів, який замовляє певні товари, роботи чи послуги (цінності), або подає заявку про придбання чи замовлення товарів, робіт чи послуг (цінностей) у майбутньому.
